language: java
jdk: openjdk10
install:
- npm install -g newman
script:
- mvn -DskipTests clean dependency:list install
- mvn test
- >
  java -jar target/lights-out-1.0-jar-with-dependencies.jar &
  sleep 10 &&
  newman run 'docs/Lights Out API Specification.postman_collection.json' --environment 'docs/Development.postman_environment.json' --timeout 60000 &&
  kill %1
